version: '3'
networks:
  dev:
    external: true
services:
  eshop-v1:
    container_name: eshop-v1
    stdin_open: true
    restart: always
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dev